// Admin

export const GET_MANAGEUSER_DETAIL = 'GET_MANAGEUSER_DETAIL'
export const GET_SETTING_DETAIL = 'GET_SETTING_DETAIL'
export const GET_DASHBOARD_DETAIL = 'GET_DASHBOARD_DETAIL'

// User

export const GET_FEED_DETAIL = 'GET_FEED_DETAIL'
export const GET_PROFILE_DETAIL = 'GET_PROFILE_DETAIL'
export const GET_HOME_DETAIL = 'GET_HOME_DETAIL'

// Other Pages

export const GET_ABOUTUS_DETAIL = 'GET_ABOUTUS_DETAIL'
export const GET_CONTACTUS_DETAIL = 'GET_CONTACTUS_DETAIL'
export const GET_TERMANDCOND_DETAIL = 'GET_TERMANDCOND_DETAIL'



